// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BsDatePicker: typeof import('./src/components/date/BsDatePicker.vue')['default']
    DatePicker: typeof import('./src/components/date/DatePicker.vue')['default']
    DateRangePicker: typeof import('./src/components/date/DateRangePicker.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
